version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/.ci/logstash-run.sh
    environment:
      - OPENSEARCH_VERSION=$OPENSEARCH_VERSION
      - INTEGRATION=${INTEGRATION:-false}
      - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
      - OPENSEARCH_SECURITY_ENABLED=$OPENSEARCH_SECURITY_ENABLED
      - OPENSEARCH_PASSWORD=$OPENSEARCH_PASSWORD
      - OPENSEARCH_SSL_SUPPORTED_PROTOCOLS=$OPENSEARCH_SSL_SUPPORTED_PROTOCOLS

  opensearch:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.opensearch
      args:
        - OPENSEARCH_VERSION=$OPENSEARCH_VERSION
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
    command: /usr/share/opensearch/opensearch-run.sh
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    user: opensearch


# bundle exec rspec -fd --tag integration --tag es_version:6.8.18 spec/filters/integration
